sonar.projectKey=library-app
sonar.projectName=Library App
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.test.*,**/vendor/**,**/*.yaml,**/*.yml,**/*_test.go,**/mocks/**
sonar.projectBaseDir=.
sonar.go.file.suffixes=.go

sonar.host.url=${SONAR_HOST_URL}
sonar.login=${SONAR_TOKEN}

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.go.coverage.reportPaths=server/coverage.out