sonar.projectKey=library-app
sonar.projectName=Library App
sonar.sourceEncoding=UTF-8

sonar.sources=server,devops-client-app
sonar.exclusions=**/node_modules/**,**/*.test.*,**/vendor/**,**/*.yaml,**/*.yml
sonar.projectBaseDir=.
sonar.go.file.suffixes=.go
sonar.go.sources=server

sonar.host.url=${SONAR_HOST_URL}
sonar.login=${SONAR_TOKEN}

sonar.javascript.lcov.reportPaths=devops-client-app/coverage/lcov.info
sonar.go.coverage.reportPaths=server/coverage.out