apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: IMAGE_CLIENT_PLACEHOLDER
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: http://server:8080/api
      imagePullSecrets:
        - name: yandex-registry
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
  ports:
    - port: 3000
      targetPort: 3000