apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
        - name: yc-registry-secret
      containers:
        - name: client
          image: cr.yandex/crpiegiuj22g2courr8t/client:df59496f6c8f71cdbba777865f01e6bd165207cb
          ports:
            - containerPort: 8080
          env:
            - name: REACT_APP_API_URL
              value: /api
