apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: default
  labels:
    app: server
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - name: http
      port: 8080        # сервис внутри кластера
      targetPort: 8080  # порт контейнера
      nodePort: 30007   # внешний порт (30000–32767)