- hosts: vm
  become: yes

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Install docker-compose
      apt:
        name: docker-compose
        state: present

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
    
    - name: Install kubectl
      become: yes
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.29.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
