name: main.yml
on:
  push

env:
  REGISTRY: ${{ secrets.YC_REGISTRY }}
  
jobs:
  build-server:
    needs: [test-server]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v6
        with:
            working-directory: server
            go-version: '1.25'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
            working-directory: server

  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: test
        working-directory: server
        run: go test ./internal/service/author/

  build-client:
    needs: [test-client]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devops-client-app 
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
        
  test-client:
    needs: [build-server-docker]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devops-client-app 
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install dependencies
        run: npm install
      - name: test
        run: npm test -- --coverage --watchAll=false
    
  build-server-docker:
      needs: [build-server]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: login
          run: |
            docker login \
              --username oauth \
              --password ${{ secrets.YC_TOKEN }} \
              cr.yandex

        - name: build
          run: docker build -t $REGISTRY/server:latest ./server

        - name: push
          run: docker push $REGISTRY/server:latest
  
  build-client-docker:
    needs: [build-client]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: login
        run: |
          docker login \
            --username oauth \
            --password ${{ secrets.YC_TOKEN }} \
            cr.yandex

      - name: build
        run: docker build -t $REGISTRY/client:latest ./devops-client-app

      - name: push
        run: docker push $REGISTRY/client:latest

  deploy-k8s:
    needs: [build-client-docker]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.27.0'

      - name: login to Yandex Container Registry
        run: |
          echo "${{ secrets.YC_IAM_TOKEN }}" | docker login cr.yandex -u iam -p- 

      - name: replace placeholders in YAML
        run: |
          sed -i "s|IMAGE_SERVER_PLACEHOLDER|cr.yandex/${{ secrets.YC_REGISTRY_ID }}/server:latest|g" k8s/server.yaml
          sed -i "s|IMAGE_CLIENT_PLACEHOLDER|cr.yandex/${{ secrets.YC_REGISTRY_ID }}/client:latest|g" k8s/client.yaml

      - name: apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/db.yaml
          kubectl apply -f k8s/server.yaml
          kubectl apply -f k8s/client.yaml
          kubectl apply -f k8s/nginx.yaml