name: main.yml
on:
  push

env:
  REGISTRY: ${{ secrets.YC_REGISTRY }}
  
jobs:
  build-server:
    needs: [test-server]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v6
        with:
            working-directory: server
            go-version: '1.25'
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
            working-directory: server

  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Test
        working-directory: server
        run: go test ./internal/service/author/

  build-client:
    needs: [test-client]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devops-client-app 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        
  test-client:
    needs: [build-server-docker]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devops-client-app 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test -- --coverage --watchAll=false
    
  build-server-docker:
      needs: [build-server]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Login
          run: |
            docker login \
              --username oauth \
              --password ${{ secrets.YC_TOKEN }} \
              cr.yandex

        - name: Build
          run: docker build -t $REGISTRY/server:latest ./server

        - name: Push
          run: docker push $REGISTRY/server:latest
  
  build-client-docker:
    needs: [build-client]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login
        run: |
          docker login \
            --username oauth \
            --password ${{ secrets.YC_TOKEN }} \
            cr.yandex

      - name: Build
        run: docker build -t $REGISTRY/client:latest ./devops-client-app

      - name: Push
        run: docker push $REGISTRY/client:latest

  deploy-k8s:
    needs: [build-client-docker]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Replace placeholders in YAML
        run: |
          sed -i "s|IMAGE_SERVER_PLACEHOLDER|cr.yandex/${{ secrets.YC_REGISTRY_ID }}/server:latest|g" k8s/server.yaml
          sed -i "s|IMAGE_CLIENT_PLACEHOLDER|cr.yandex/${{ secrets.YC_REGISTRY_ID }}/client:latest|g" k8s/client.yaml

      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "k8s/*"
          target: "~/app/"

      - name: Deploy on VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker login --username oauth --password ${{ secrets.YC_TOKEN }} cr.yandex

            cd ~/app

            kubectl apply -f db.yaml
            kubectl apply -f server.yaml
            kubectl apply -f client.yaml
            kubectl apply -f nginx.yaml