name: main.yml
on:
  push

env:
  REGISTRY: ${{ secrets.YC_REGISTRY }}
  
jobs:
  sonar-analysis:
    needs: [test-client]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java (required for sonar scanner)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install SonarScanner
          run: |
            curl -sSLo sonar.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar.zip
            echo "$PWD/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Test + coverage
        run: |
          cd server
          go test ./... -coverprofile=coverage.out

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Client test + coverage
        run: |
          cd devops-client-app
          npm install
          npm test -- --coverage --watchAll=false

      - name: Sonar Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=library-app \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.go.coverage.reportPaths=server/coverage.out \
            -Dsonar.javascript.lcov.reportPaths=devops-client-app/coverage/lcov.info \
            -Dsonar.qualitygate.wait=true
  build-server:
    needs: [sonar-analysis]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v6
        with:
            working-directory: server
            go-version: '1.25'
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
            working-directory: server

  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Test
        working-directory: server
        run: go test ./internal/service/author/ -coverprofile=coverage.out

  build-client:
    needs: [build-server]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devops-client-app 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        
  test-client:
    needs: [test-server]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devops-client-app 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test -- --coverage --watchAll=false
    
  build-server-docker:
      needs: [build-client-docker]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Login
          run: |
            docker login \
              --username oauth \
              --password ${{ secrets.YC_TOKEN }} \
              cr.yandex

        - name: Build
          run: docker build -t $REGISTRY/server:latest ./server

        - name: Push
          run: docker push $REGISTRY/server:latest
  
  build-client-docker:
    needs: [build-client]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login
        run: |
          docker login \
            --username oauth \
            --password ${{ secrets.YC_TOKEN }} \
            cr.yandex

      - name: Build
        run: docker build -t $REGISTRY/client:latest ./devops-client-app

      - name: Push
        run: docker push $REGISTRY/client:latest
